"""Structured operation contract between a reasoning engine and Master.

This is the boundary a future reasoning engine will speak across. It sits
directly above Master:

    ReasoningInterface   structured operations, approval, structured results
      |
      v
    Master               orchestration API, structured arguments only
      |
      v
    ProjectManager / WorkManager
      |
      v
    ProjectState
      |
      v
    filesystem / YAML

The purpose is to make the reasoning side of the system pure data. A future
engine should be able to emit something like::

    {
        "operation": "create_task",
        "project_id": "ai-system",
        "task_id": "foundation-005",
        "milestone": "foundation",
        "title": "Build reasoning interface",
    }

and nothing more. That payload carries no authority. It is a *request*, it is
structurally checked here, and it only becomes a state change after a caller
explicitly approves it and it is handed to Master.

Why the vocabulary is explicit
-----------------------------
The operations below are an allowlist written out by hand, mapping names to
Master methods that already exist. Nothing is generated by reflecting over
Master, and that is deliberate: this module is a permission surface, so adding
a method to Master must not silently widen what a reasoning engine may call.
A new Master capability stays unavailable until someone writes it down here.

The table is pinned to Master's real signatures by a conformance test, so it
cannot silently drift away from the API it claims to expose.

Two kinds of checking, kept apart
---------------------------------
Request validation, which lives here, asks only: is this shaped like something
Master accepts? Is the operation known, are the required arguments present, are
the values plain scalars, is an update actually changing anything?

Domain validation, which lives in WorkManager, asks: is this a good idea right
now? Does the milestone exist, is the status one of the permitted values, is
this title non-blank.

The line is deliberate and worth stating plainly. A missing ``title`` is a
malformed request and is refused here. A ``create_task`` naming a milestone
that does not exist is a perfectly well-formed request that Master is right to
reject. This module never second-guesses the second kind of question, because a
rule copied into two places is a rule that will eventually disagree with
itself.

Update arguments
----------------
``update_milestone`` and ``update_task`` accept arbitrary field names. That is
not a gap in the check above: Master itself takes ``**changes`` and forwards
them to WorkManager, which owns the list of mutable fields. Rejecting unknown
field names here would mean copying that list out of ``core.work_manager`` and
keeping it in sync, which is exactly the duplication described above. So the
structure of an update is checked here and the vocabulary of its fields stays
where it already lives.

Batch execution is not a transaction
------------------------------------
``execute_batch`` runs its operations in order and keeps going after a failure,
because the individual results are the point. If the first two operations write
and the third does not, the first two writes are already on disk and stay
there. ``BatchResult`` reports that honestly through per-operation results and
``all_successful``; it offers no rollback, because there is none. Treating a
batch as all-or-nothing would require transactions, which this stage
deliberately does not have.

No model, no execution
----------------------
Nothing here knows about any model or provider, and nothing runs commands. This
module cannot write YAML, reach ProjectState, instantiate WorkManager, import
subprocess, or touch a path the caller did not name, because it imports none of
those things. It holds a Master and calls its public methods. The reasoning
engine proposes; Master disposes.
"""

import sys
from collections.abc import Mapping
from dataclasses import dataclass, replace
from enum import Enum
from pathlib import Path
from types import MappingProxyType

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from core.master import EXPECTED_ERRORS, Master

__all__ = [
    "ApprovalState",
    "BatchResult",
    "InvalidOperationError",
    "Operation",
    "OperationResult",
    "OperationSpec",
    "ReasoningInterface",
    "RequestError",
    "ResultStatus",
    "SPECS",
    "Decision",
    "MasterDecision",
]


# Values a request may carry. A reasoning engine emitting JSON can only produce
# these, and refusing anything else here keeps an unexpected object from being
# passed down to Master as an argument.
SCALAR_TYPES = (str, int, float, bool)


class RequestError(Enum):
    """Why a request is not structurally valid, or was not allowed to run.

    An enum rather than a message so a caller can branch on the reason without
    matching on error text.
    """

    NOT_A_MAPPING = "not_a_mapping"
    MISSING_OPERATION = "missing_operation"
    UNKNOWN_OPERATION = "unknown_operation"
    MISSING_ARGUMENT = "missing_argument"
    UNEXPECTED_ARGUMENT = "unexpected_argument"
    INVALID_ARGUMENT_VALUE = "invalid_argument_value"
    NO_CHANGES = "no_changes"
    NOT_APPROVED = "not_approved"
    EXPLICITLY_REJECTED = "explicitly_rejected"


class ResultStatus(Enum):
    """Outcome of an execution attempt."""

    SUCCESS = "success"
    INVALID_REQUEST = "invalid_request"
    DOMAIN_ERROR = "domain_error"
    REJECTED = "rejected"


class ApprovalState(Enum):
    """Where an operation sits in the propose / approve / execute sequence."""

    PROPOSED = "proposed"
    APPROVED = "approved"
    REJECTED = "rejected"


class Decision(Enum):
    """High-level Master decision."""

    ACT = "act"
    WAIT = "wait"
    BLOCKED = "blocked"
    NEEDS_INFORMATION = "needs_information"
    REQUEST_APPROVAL = "request_approval"




class InvalidOperationError(ValueError):
    """Raised when a payload is not a structurally valid Master request.

    Carries a :class:`RequestError` so callers react to the kind of problem
    rather than to the wording. Subclasses ValueError to match the convention
    the rest of the system uses for rejected input.
    """

    def __init__(self, reason, message, operation=None):
        super().__init__(message)
        self.reason = reason
        self.operation = operation


@dataclass(frozen=True)
class OperationSpec:
    """How one named operation maps onto an existing Master method.

    ``required`` and ``optional`` name Master's parameters. ``variadic`` marks a
    Master method that ends in ``**changes``, where any further argument is
    passed through untouched for the domain layer to judge.
    """

    method: str
    required: tuple
    optional: tuple = ()
    variadic: bool = False

    @property
    def accepted(self):
        return frozenset(self.required) | frozenset(self.optional)


# The allowlist. Every method named here already exists on Master, and exposes
# nothing Master does not already support.
SPECS = MappingProxyType(
    {
        "inspect_project": OperationSpec("status", ("project_id",)),
        "create_milestone": OperationSpec(
            "create_milestone",
            ("project_id", "milestone_id", "name"),
            ("status",),
        ),
        "update_milestone": OperationSpec(
            "update_milestone",
            ("project_id", "milestone_id"),
            variadic=True,
        ),
        "create_task": OperationSpec(
            "create_task",
            ("project_id", "task_id", "milestone", "title"),
            ("status", "assigned_to"),
        ),
        "update_task": OperationSpec(
            "update_task",
            ("project_id", "task_id"),
            variadic=True,
        ),
    }
)



@dataclass(frozen=True)
class MasterDecision:
    """An explicit Master decision returned by the reasoning layer."""

    decision: Decision
    reason: str = ""
    operation: "Operation | None" = None

    def __post_init__(self):
        if not isinstance(self.reason, str):
            object.__setattr__(self, "reason", str(self.reason) if self.reason is not None else "")
        # Validate rules
        if self.decision is Decision.ACT:
            if self.operation is None:
                raise InvalidOperationError(
                    RequestError.INVALID_ARGUMENT_VALUE,
                    "act requires an operation",
                )
        elif self.decision in (Decision.WAIT, Decision.BLOCKED, Decision.NEEDS_INFORMATION):
            if self.operation is not None:
                raise InvalidOperationError(
                    RequestError.INVALID_ARGUMENT_VALUE,
                    f"{self.decision.value} requires no operation",
                )
        elif self.decision is Decision.REQUEST_APPROVAL:
            if self.operation is None:
                raise InvalidOperationError(
                    RequestError.INVALID_ARGUMENT_VALUE,
                    "request_approval requires an operation",
                )


@dataclass(frozen=True)
class Operation:
    """A structurally valid request, held until a caller approves it.

    Immutable: ``approve`` and ``reject`` return new instances, so an approved
    operation cannot be flipped back to proposed, and nothing can mutate an
    operation between approval and execution.
    """

    operation: str
    arguments: Mapping
    state: ApprovalState = ApprovalState.PROPOSED

    def __post_init__(self):
        object.__setattr__(self, "arguments", MappingProxyType(dict(self.arguments)))

    @classmethod
    def propose(cls, payload):
        """Validate a reasoning payload and return it as a proposed Operation.

        payload is the flat mapping a reasoning engine emits: an ``operation``
        key plus the arguments for that operation. Raises
        :class:`InvalidOperationError` if it is not structurally a Master
        request. Nothing is executed and no state is touched.
        """
        if not isinstance(payload, Mapping):
            raise InvalidOperationError(
                RequestError.NOT_A_MAPPING,
                f"request must be a mapping, got {type(payload).__name__}",
            )

        if "operation" not in payload:
            raise InvalidOperationError(
                RequestError.MISSING_OPERATION, "request is missing 'operation'"
            )

        name = payload["operation"]
        if not isinstance(name, str):
            raise InvalidOperationError(
                RequestError.INVALID_ARGUMENT_VALUE,
                "'operation' must be a string",
            )

        spec = SPECS.get(name)
        if spec is None:
            raise InvalidOperationError(
                RequestError.UNKNOWN_OPERATION,
                f"unknown operation {name!r}",
                operation=name,
            )

        arguments = {key: value for key, value in payload.items() if key != "operation"}

        missing = [key for key in spec.required if key not in arguments]
        if missing:
            raise InvalidOperationError(
                RequestError.MISSING_ARGUMENT,
                f"{name} is missing required argument(s): {', '.join(sorted(missing))}",
                operation=name,
            )

        for key, value in arguments.items():
            if value is not None and not isinstance(value, SCALAR_TYPES):
                raise InvalidOperationError(
                    RequestError.INVALID_ARGUMENT_VALUE,
                    f"argument {key!r} must be a scalar or None, "
                    f"got {type(value).__name__}",
                    operation=name,
                )

        if spec.variadic:
            changes = [key for key in arguments if key not in spec.required]
            if not changes:
                raise InvalidOperationError(
                    RequestError.NO_CHANGES,
                    f"{name} requires at least one field to change",
                    operation=name,
                )
        else:
            unexpected = sorted(set(arguments) - spec.accepted)
            if unexpected:
                raise InvalidOperationError(
                    RequestError.UNEXPECTED_ARGUMENT,
                    f"{name} does not accept argument(s): {', '.join(unexpected)}",
                    operation=name,
                )

        return cls(operation=name, arguments=arguments)

    def approve(self):
        """Return an approved copy. Approval is explicit and never automatic."""
        return replace(self, state=ApprovalState.APPROVED)

    def reject(self):
        """Return a rejected copy."""
        return replace(self, state=ApprovalState.REJECTED)

    @property
    def is_approved(self):
        return self.state is ApprovalState.APPROVED


@dataclass(frozen=True)
class OperationResult:
    """The outcome of one operation, inspectable without reading any message."""

    operation: str
    status: ResultStatus
    value: object = None
    reason: RequestError = None
    error_type: str = None
    message: str = None

    @property
    def succeeded(self):
        return self.status is ResultStatus.SUCCESS

    @classmethod
    def success(cls, operation, value):
        return cls(operation=operation, status=ResultStatus.SUCCESS, value=value)

    @classmethod
    def invalid_request(cls, operation, error):
        return cls(
            operation=operation,
            status=ResultStatus.INVALID_REQUEST,
            reason=error.reason,
            message=str(error),
        )

    @classmethod
    def domain_error(cls, operation, error):
        return cls(
            operation=operation,
            status=ResultStatus.DOMAIN_ERROR,
            error_type=type(error).__name__,
            message=str(error),
        )

    @classmethod
    def not_executed(cls, operation, state, reason):
        return cls(
            operation=operation,
            status=ResultStatus.REJECTED,
            reason=reason,
            message=f"operation is {state.value}",
        )


@dataclass(frozen=True)
class BatchResult:
    """Per-operation outcomes of a batch, in the order they were attempted.

    Not a transaction. ``all_successful`` is False as soon as one operation
    failed, and any operation that already succeeded stays applied; there is no
    rollback and none is implied.
    """

    results: tuple

    def __len__(self):
        return len(self.results)

    @property
    def all_successful(self):
        return all(result.succeeded for result in self.results)

    @property
    def succeeded(self):
        return tuple(r for r in self.results if r.succeeded)

    @property
    def failed(self):
        return tuple(r for r in self.results if not r.succeeded)


class ReasoningInterface:
    """The controlled boundary a reasoning engine proposes operations through.

    Wraps a Master and nothing else. It cannot write storage, reach
    ProjectState, or run commands: it holds one Master reference and calls its
    public methods.

    Nothing is executed automatically. A caller proposes, inspects, approves,
    then executes.
    """

    def __init__(self, master=None):
        if master is None:
            master = Master()
        if not isinstance(master, Master):
            raise TypeError(
                f"expected a Master, got {type(master).__name__}"
            )
        self._master = master

    @property
    def master(self):
        return self._master

    def propose(self, payload):
        """Validate a payload into a proposed Operation without executing it."""
        return Operation.propose(payload)

    def execute(self, operation):
        """Execute an approved Operation through Master.

        Returns an :class:`OperationResult` for every outcome, including
        failure. A proposed or rejected operation is not executed at all and
        comes back as ``REJECTED``. Domain errors are reported as
        ``DOMAIN_ERROR`` carrying the originating exception's type name.
        Anything outside Master's expected error set propagates, so a real bug
        is not disguised as a rejected request.
        """
        if not isinstance(operation, Operation):
            raise TypeError(
                f"expected an Operation, got {type(operation).__name__}"
            )

        if not operation.is_approved:
            reason = (
                RequestError.NOT_APPROVED
                if operation.state is ApprovalState.PROPOSED
                else RequestError.EXPLICITLY_REJECTED
            )
            return OperationResult.not_executed(
                operation.operation, operation.state, reason
            )

        spec = SPECS[operation.operation]
        arguments = dict(operation.arguments)

        if spec.variadic:
            call_kwargs = {key: arguments.pop(key) for key in spec.required}
            call_kwargs.update(arguments)
        else:
            call_kwargs = arguments

        method = getattr(self._master, spec.method)
        try:
            value = method(**call_kwargs)
        except EXPECTED_ERRORS as error:
            return OperationResult.domain_error(operation.operation, error)

        return OperationResult.success(operation.operation, value)

    def execute_batch(self, operations):
        """Attempt several operations in order, collecting one result each.

        Accepts Operations and raw payloads. A payload is proposed first; if it
        is malformed it becomes an ``INVALID_REQUEST`` result rather than
        aborting the batch.

        Execution is sequential and is NOT atomic. A failure does not stop the
        run and does not undo anything already applied, so partial progress is
        visible in the returned results instead of being hidden behind an
        all-or-nothing promise this layer cannot keep.
        """
        results = []
        for item in operations:
            if isinstance(item, Operation):
                operation = item
            else:
                try:
                    operation = Operation.propose(item)
                except InvalidOperationError as error:
                    name = error.operation
                    if name is None and isinstance(item, Mapping):
                        candidate = item.get("operation")
                        name = candidate if isinstance(candidate, str) else None
                    results.append(OperationResult.invalid_request(name, error))
                    continue
            results.append(self.execute(operation))

        return BatchResult(results=tuple(results))